[config]
model = "gemini/gemini-2.0-flash-001"
fallback_models = ["gemini/gemini-2.5-flash"]
custom_model_max_tokens = 32000

[github_action_config]
auto_review = true
auto_describe = true
auto_improve = true

[pr_reviewer]
require_tests_review = false
num_code_suggestions = 4
