[config]
model = "gemini/gemini-2.0-flash"
fallback_models = ["gemini/gemini-1.5-flash"]

[github_action_config]
auto_review = true
auto_describe = true
auto_improve = true

[pr_reviewer]
require_tests_review = false
num_code_suggestions = 4
