apiVersion: v1
kind: ConfigMap
metadata:
  name: arcana-config
  namespace: arcana-cloud
data:
  database.url: jdbc:mysql://mysql-service:3306/arcana_cloud?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  database.username: arcana
  redis.host: redis-service
  redis.port: "6379"
  deployment.mode: layered
  communication.protocol: grpc
  service.grpc.url: arcana-service:9090
  repository.grpc.url: arcana-repository:9091
