apiVersion: v1
kind: Service
metadata:
  name: arcana-controller
  namespace: arcana-cloud
  labels:
    app: arcana-controller
spec:
  selector:
    app: arcana-controller
    layer: controller
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: arcana-service
  namespace: arcana-cloud
  labels:
    app: arcana-service
spec:
  selector:
    app: arcana-service
    layer: service
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  - name: grpc
    port: 9090
    targetPort: 9090
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: arcana-repository
  namespace: arcana-cloud
  labels:
    app: arcana-repository
spec:
  selector:
    app: arcana-repository
    layer: repository
  ports:
  - name: http
    port: 8082
    targetPort: 8082
  - name: grpc
    port: 9091
    targetPort: 9091
  type: ClusterIP
